import re 
from models .cookie import Cookie 

class CookieParser :
    def __init__ (self ):
        try :
            from utils .logger import log_manager 
            self .logger =log_manager .get_logger ('cookie_parser')
        except :
            import logging 
            self .logger =logging .getLogger ('cookie_parser')


        self ._cookie_pattern =re .compile (r'([^=]+)=([^;]+)')

    def parse (self ,content ):
        cookies =[]


        lines =content .strip ().split ('\n')
        parsed_count =0 
        error_count =0 

        for line in lines :
            line =line .strip ()
            if not line or line .startswith ('#'):
                continue 

            parts =line .split ('\t')

            if len (parts )>=7 :

                try :
                    expires_value =int (parts [4 ])
                except (ValueError ,IndexError )as e :
                    self .logger .debug (f'Invalid expires value for {parts [5 ]}: {str (e )}')
                    expires_value =0 
                    error_count +=1 

                try :
                    cookie =Cookie (
                    domain =parts [0 ],
                    include_subdomains =parts [1 ]=='TRUE',
                    path =parts [2 ],
                    secure =parts [3 ]=='TRUE',
                    expires =expires_value ,
                    name =parts [5 ],
                    value =parts [6 ]if len (parts )>6 else '',
                    http_only =parts [7 ]=='TRUE'if len (parts )>7 else False 
                    )
                    cookies .append (cookie )
                    parsed_count +=1 
                except Exception as e :
                    self .logger .debug (f'Error parsing cookie line: {str (e )}')
                    error_count +=1 
            else :

                self ._parse_alternative_format (line ,cookies )

        self .logger .debug (f'Parsed {parsed_count } cookies, {error_count } errors')
        return cookies 

    def _parse_alternative_format (self ,line ,cookies ):
        matches =self ._cookie_pattern .findall (line )

        for name ,value in matches :
            try :
                cookie =Cookie (
                domain ='unknown',
                include_subdomains =False ,
                path ='/',
                secure =False ,
                expires =0 ,
                name =name .strip (),
                value =value .strip ()
                )
                cookies .append (cookie )
            except Exception as e :
                self .logger .debug (f'Error parsing alternative format: {str (e )}')

    def export_netscape (self ,cookies ):
        output ='# Netscape HTTP Cookie File\n'
        output +='# https://curl.se/docs/http-cookies.html\n'
        output +='# This file was generated by Cookie Analyzer API\n\n'

        for cookie in cookies :
            output +=f'{cookie .domain }\t'
            output +=f'{str (cookie .include_subdomains ).upper ()}\t'
            output +=f'{cookie .path }\t'
            output +=f'{str (cookie .secure ).upper ()}\t'
            output +=f'{cookie .expires }\t'
            output +=f'{cookie .name }\t'
            output +=f'{cookie .value }\n'

        return output 

    def export_csv (self ,cookies ):
        output ='Domain,IncludeSubdomains,Path,Secure,Expires,Name,Value\n'

        for cookie in cookies :
            output +=f'{cookie .domain },'
            output +=f'{cookie .include_subdomains },'
            output +=f'{cookie .path },'
            output +=f'{cookie .secure },'
            output +=f'{cookie .expires },'
            output +=f'{cookie .name },'
            output +=f'{cookie .value }\n'

        return output 